---
#   ____             __ _
#  / ___|___  _ __  / _(_) __ _
# | |   / _ \| '_ \| |_| |/ _` |
# | |__| (_) | | | |  _| | (_| |
#  \____\___/|_| |_|_| |_|\__, |
#                         |___/


configure_homebrew: true
configure_dotfiles: true
configure_extras: true
configure_macos: true

# ==============================================================================
# Homebrew
# ==============================================================================

homebrew_path_prefix: "{{ (ansible_machine == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}"

homebrew_packages:
  - zsh-syntax-highlighting
  - zsh-history-substring-search
  - coreutils
  - exa
  - wget
  - nano
  - git
  - php
  - composer
  - cloudflared

homebrew_casks:
  - onedrive
  - arc
  - discord
  - spotify
  - iina
  - obsidian
  - visual-studio-code
  - httpie
  - docker
  - affinity-photo
  - affinity-designer

# ==============================================================================
# Extras
# ==============================================================================

vscode_extensions:
  - equinusocio.vsc-material-theme
  - pkief.material-icon-theme
  - ms-azuretools.vscode-docker
  - natizyskunk.sftp
  - jock.svg
  - editorconfig.editorconfig
  - stylelint.vscode-stylelint
  - dbaeumer.vscode-eslint
  - dotenv.dotenv-vscode
  - bmewburn.vscode-intelephense-client
  - bradlc.vscode-tailwindcss
  - astro-build.astro-vscode
