---
#  _   _                      _
# | | | | ___  _ __ ___   ___| |__  _ __ _____      __
# | |_| |/ _ \| '_ ` _ \ / _ \ '_ \| '__/ _ \ \ /\ / /
# |  _  | (_) | | | | | |  __/ |_) | | |  __/\ V  V /
# |_| |_|\___/|_| |_| |_|\___|_.__/|_|  \___| \_/\_/


- name: Check if Homebrew is installed
  ansible.builtin.stat:
    path: /opt/homebrew/bin/brew
  register: brew_binary
  check_mode: false

- name: Fetch and run Homebrew install script
  ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: not brew_binary.stat.exists

- name: Install Homebrew packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_packages }}"

- name: Install Homebrew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    install_options: "appdir=/Applications"
    sudo_password: "{{ ansible_become_password | default(omit) }}"
    state: present
  loop: "{{ homebrew_casks }}"
