---
#  ____                 _                                  _
# |  _ \  _____   _____| | ___  _ __  _ __ ___   ___ _ __ | |_
# | | | |/ _ \ \ / / _ \ |/ _ \| '_ \| '_ ` _ \ / _ \ '_ \| __|
# | |_| |  __/\ V /  __/ | (_) | |_) | | | | | |  __/ | | | |_
# |____/ \___| \_/ \___|_|\___/| .__/|_| |_| |_|\___|_| |_|\__|
#                              |_|


# ==============================================================================
# VS Code
# ==============================================================================

- name: Install VS Code extensions.
  command: /opt/homebrew/bin/code --install-extension {{ item }}
  loop: "{{ vscode_extensions }}"
  register: vscode_extension
  changed_when: "'successfully installed' in vscode_extension.stdout"

# ==============================================================================
# Rust
# ==============================================================================

- name: Check if Rustup is installed.
  stat:
    path: "{{ ansible_env.HOME }}/.local/bin/rustup/cargo/bin/rustup"
  register: rustup_binary
  check_mode: false

- name: Fetch and run rustup install script.
  shell: curl -fsSL https://sh.rustup.rs | sh -s -- -y --no-modify-path
  environment:
    RUSTUP_HOME: "{{ ansible_env.HOME }}/.local/bin/rustup"
    CARGO_HOME: "{{ ansible_env.HOME }}/.local/bin/rustup/cargo"
  when: not rustup_binary.stat.exists

# ==============================================================================
# PNPM / NodeJS
# ==============================================================================

- name: Check if pnpm is installed.
  stat:
    path: "{{ ansible_env.HOME }}/.local/bin/pnpm/pnpm"
  register: pnpm_binary
  check_mode: false

- name: Fetch and run pnpm install script.
  shell: curl -sSf https://get.pnpm.io/install.sh | sh -s
  environment:
    PNPM_HOME: "{{ ansible_env.HOME }}/.local/bin/pnpm"
    ZDOTDIR: "{{ ansible_env.HOME }}/.config/zsh"
  when: not pnpm_binary.stat.exists

- name: Remove pnpm lines from ".zshrc".
  replace:
    regexp: "(# pnpm)((.|\n)*)(# pnpm end)"
    path: "{{ ansible_env.HOME }}/.config/zsh/.zshrc"
  when: not pnpm_binary.stat.exists

- name: Install NodeJS LTS.
  shell: "pnpm env use --global lts"
  environment:
    PNPM_HOME: "{{ ansible_env.HOME }}/.local/bin/pnpm"
    PATH: "$PATH:{{ ansible_env.HOME }}/.local/bin/pnpm"
  when: not pnpm_binary.stat.exists
