---
#      _       _    __ _ _
#   __| | ___ | |_ / _(_) | ___  ___
#  / _` |/ _ \| __| |_| | |/ _ \/ __|
# | (_| | (_) | |_|  _| | |  __/\__ \
#  \__,_|\___/ \__|_| |_|_|\___||___/


- name: Ensure that all required directories are in place
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  loop:
    - .cache
    - .cache/zsh
    - .cache/psql
    - .cache/node
    - .local
    - .local/bin
    - .local/share
    - .local/state
    - Library/Application Support/Code/User
    - Projects

- name: Copy dotfiles to home directory
  copy:
    src: "{{ playbook_dir }}/../home/"
    dest: "{{ ansible_env.HOME }}"

- name: Copy VS Code settings
  copy:
    src: "{{ playbook_dir }}/../misc/vscode-settings.json"
    dest: "{{ ansible_env.HOME }}/Library/Application Support/Code/User/settings.json"
