---
#  _   _                      _
# | | | | ___  _ __ ___   ___| |__  _ __ _____      __
# | |_| |/ _ \| '_ ` _ \ / _ \ '_ \| '__/ _ \ \ /\ / /
# |  _  | (_) | | | | | |  __/ |_) | | |  __/\ V  V /
# |_| |_|\___/|_| |_| |_|\___|_.__/|_|  \___| \_/\_/


# ==============================================================================
# Setup
# ==============================================================================

- name: Ensure Homebrew parent directory is in place.
  file:
    path: "/opt/homebrew"
    state: directory
    owner: "{{ ansible_user_id }}"

- name: Ensure Homebrew directories are in place.
  file:
    path: "/opt/homebrew/{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  loop:
    - Caskroom
    - Cellar
    - Frameworks
    - Homebrew
    - bin
    - etc
    - include
    - lib
    - opt
    - sbin
    - share
    - share/zsh
    - share/zsh/site-functions
    - var

- name: Clone Homebrew repository.
  git:
    repo: https://github.com/Homebrew/brew
    dest: "/opt/homebrew/Homebrew"
    version: master
    depth: 1
    update: false

- name: Check if Homebrew binary is in place.
  stat: "path=/opt/homebrew/bin/brew"
  register: homebrew_binary
  check_mode: false

- name: Symlink Homebrew binary to "homebrew_path_bin".
  file:
    src: "/opt/homebrew/Homebrew/bin/brew"
    dest: "/opt/homebrew/bin/brew"
    state: link
  when: not homebrew_binary.stat.exists

# ==============================================================================
# Packages / Casks
# ==============================================================================

- name: Install Homebrew packages.
  homebrew:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    install_options: "{{ item.install_options | default(omit) }}"
  loop: "{{ homebrew_packages }}"

- name: Install Homebrew casks.
  homebrew_cask:
    name: "{{ item.name | default(item) }}"
    state: present
    install_options: "{{ item.install_options | default('appdir=/Applications') }}"
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  loop: "{{ homebrew_casks }}"
